name: Notion Sync

on:
    repository_dispatch:
        types: [notion-sync]

permissions:
    contents: write

jobs:
    sync:
        runs-on: ubuntu-latest

        env:
            NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
            NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Run Notion Sync Script
              run: bun run notion:sync

            - name: Commit & Push
              run: |
                  git config user.name "notion-bot"
                  git config user.email "notion-bot@users.noreply.github.com"

                  git add .

                  # 추가/수정 파일
                  ADDED_FILES=$(git diff --cached --name-only --diff-filter=ACM | \
                  grep '\.mdx$' || true)

                  ADDED_FILES=$(echo "$ADDED_FILES" | \
                  xargs -r -n1 basename | \
                  paste -sd ", " -)

                  # 삭제 파일
                  DELETED_FILES=$(git diff --cached --name-only --diff-filter=D | \
                  grep '\.mdx$' || true)

                  DELETED_FILES=$(echo "$DELETED_FILES" | \
                  xargs -r -n1 basename | \
                  paste -sd ", " -)

                  DATE=$(TZ=Asia/Seoul date "+%y년 %-m월 %-d일 %-H시 %-M분")

                  # 메시지 조합
                  if [ -z "$ADDED_FILES" ] && [ -z "$DELETED_FILES" ]; then
                  COMMIT_MSG="노션 문서 내용 반영 ($DATE)"
                  else
                  PARTS=""

                  if [ -n "$ADDED_FILES" ]; then
                      PARTS="[$ADDED_FILES]"
                  fi

                  if [ -n "$DELETED_FILES" ]; then
                      if [ -n "$PARTS" ]; then
                      PARTS="$PARTS [삭제: $DELETED_FILES]"
                      else
                      PARTS="[삭제: $DELETED_FILES]"
                      fi
                  fi

                  COMMIT_MSG="$PARTS 노션 문서 내용 반영 ($DATE)"
                  fi

                  git commit -m "$COMMIT_MSG" || echo "변경된 데이터가 없습니다 ($DATE)"
                  git push
